# Generated by Django 2.2.10 on 2021-02-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210202_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
    ]
