# Generated by Django 2.2.10 on 2021-02-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210202_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='finish',
            field=models.DateTimeField(verbose_name='Окончание'),
        ),
    ]
