# Generated by Django 2.2.10 on 2021-02-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20210202_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='text',
            field=models.TextField(default='', verbose_name='Текст'),
        ),
    ]
