version: '3.7'

services:
  app:
    container_name: polls
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./app/.env
    volumes:
      - ./app/:/usr/src/app/
    ports: 
      - 8000:8000  
    depends_on:
      - db

  db:
    restart: always
    container_name: polls_db
    image: postgres:12-alpine
    volumes:
      - ./app/data:/var/lib/postgresql/data/
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=polls

volumes: 
  data: